samplesets:
  - AG1000G-AO
  - AG1000G-BF-A
  - AG1000G-BF-B
  - AG1000G-BF-C
  - AG1000G-CD
  - AG1000G-CF
  - AG1000G-CI
  - AG1000G-CM-A
  - AG1000G-CM-B
  - AG1000G-CM-C
  - AG1000G-FR
  - AG1000G-GA-A
  - AG1000G-GH
  - AG1000G-GM-A
  - AG1000G-GM-B
  - AG1000G-GM-C
  - AG1000G-GN-A
  - AG1000G-GN-B
  - AG1000G-GQ
  - AG1000G-GW
  - AG1000G-KE
  - AG1000G-ML-A
  - AG1000G-ML-B
  - AG1000G-MW
  - AG1000G-MZ
  - AG1000G-TZ
  - AG1000G-UG
  - AG1000G-X
